title: Simple for Tests
description: simple4tests aims to provide methodology and simple tools to support developers and testers while building maintainable and reliable automated tests
theme: jekyll-theme-cayman